matrix:
  include:
  - os: linux
    language: android
    script: flutter build apk --debug
    android:
      components:
      - build-tools-28.0.3
      - android-27
      - android-28
install:
- git clone https://github.com/flutter/flutter
- export PATH="$PATH:`pwd`/flutter/bin"
- flutter doctor
- flutter packages get
after_script: ls
before_install:
- openssl aes-256-cbc -K $encrypted_2a7efc7cf3dc_key -iv $encrypted_2a7efc7cf3dc_iv -in secrets.tar.enc -out ./secrets.tar -d
- tar xvf secrets.tar
- mv key.properties android
- mv google-services.json android/app

notifications:
  email: false

if: branch = master AND type = push AND fork = false
